sample-apps/00-fluentBit/kubernetes/fluentbit.yaml
Added fluent bit config to parse traceId from logs
=> Added fluent bit config to parse traceId from logs

sample-apps/00-fluentBit/kubernetes/fluentbit.yaml
Parsing span_id & service anme
=> Parsing span_id & service anme

cf-templates/stack.yaml, eks-setup.sh, scripts/eks-setup.sh
Wrapped up EKs setup in one script, reducing manual step
=> Wrapped up EKs setup in one script

sample-apps/11-client/src/App.tsx, sample-apps/11-client/src/components/Cards.tsx, sample-apps/11-client/src/components/Image.tsx, sample-apps/11-client/src/components/Links.tsx, sample-apps/11-client/src/components/Payment.tsx, sample-apps/11-client/src/components/Status.tsx, sample-apps/11-client/src/components/Tools.tsx, sample-apps/11-client/src/index.tsx
Functions calls to clean state, to generate traces for `/checkout` endpoint.
=> Fix state calls

sample-apps/11-client/api/api.py
- Workaround increasing storage;
- Made a little cosmetic refactor, placing all api endpoints in alphabetic order to better navigate on changes.
=> fix: increasing storage

sample-apps/05-databaseService/requirements.txt
https://github.com/aws-samples/observability-with-amazon-opensearch/issues/23
Add dependency. 
Have tested and verified the added dependency will fix the DependencyConflict issue.
=> fix #23 DependencyConflict

sample-apps/11-client/api/api.py, sample-apps/11-client/src/components/Cards.tsx
- Principal change: Unnecessary calls to `/checkout`, which was consuming products in the inventory
- Alphabetic ordering of endpoints in `11-client/api/api.py` for better readbility
=> fix: removing unnecessary calls to /checkout

cf-templates/stack.yaml
Add CFN support to workshop-studio
Add CFN support to workshop-studio
=> Add CFN support to workshop-studio

sample-apps/11-client/api/api.py
Fixed exception for Checkout which was returning Syntax Error.
=> Fixed Checkout except

sample-apps/11-client/src/App.tsx, sample-apps/11-client/src/components/Cards.tsx, sample-apps/11-client/src/components/Payment.tsx, sample-apps/11-client/src/components/Status.tsx
- [New UI] When "cancel order" is performed, "get order status" must return different from the current message or block this action;
- Improvement in performance with `useEffect` hook.
=> ui: cancel-status, performance improvements with useState

00-setup.sh, cf-templates/stack.yaml
Adding lines on setup.sh to install kubectl and configure the EKS Cluster kubeconfig.
=> [feat] adding script to configure kube config

sample-apps/11-client/src/components/Status.tsx
- Changed UI to showcase Success for cancel action.
=> ui: sucess alert on cancel

sample-apps/11-client/api/api.py
- Removed `DEBUG` mode
- Removed logs from client server
=> log: turning off client flask app

sample-apps/11-client/Dockerfile
- Added step to upgrade NPM on build
=> Node Package Manager upgrade step in Dockerfile

00-setup.sh, cf-templates/stack.yaml
I'm updating the AMI to the latest available version and tweaking the scripts to ensure the region is getting dynamically. 
=> Feat/scripts Updating the AMIs, getting the region dynamically scripts, and removing the KMS that is part of the Amazon EKS setup

cf-templates/stack.yaml, scripts/eks-setup.sh
- Updated eks-setup script by removing eks cluster creation related commands
- Integrated with SecretManager to generate unique AOS password everytime 
=> SecretManager to generate unique AOS password everytime & eks-setup script update

scripts/03-delete-ecr-repo.sh
Script to delete ECR repositories. This needs to be invoked from Cloud9 as a part of cleanup process.
=> Delete ECR repositories

sample-apps/02-otel-collector/kubernetes/01-configmap.yaml, sample-apps/02-otel-collector/kubernetes/02-deployment.yaml
This PR contemplates the correction of the entrypoint that was incorrect due to the change to the latest version of ADOT Collector.
=> Fixed OTEL Collector parameter

sample-apps/04-analytics-service/Dockerfile, sample-apps/04-analytics-service/script.sh
Dockerfile fix for analytics-service.
=> Dockerfile fix for analytics-service

cf-templates/eks.yaml
Add new policy for integration with AWS Systems Manager.
=> Add new policy for integration with AWS Systems Manager

sample-apps/01-data-prepper/kubernetes/data-prepper.yaml, sample-apps/11-client/Dockerfile
=> Explicit version setting to avoid breaking dependent components

sample-apps/05-databaseService/requirements.txt, sample-apps/06-orderService/requirements.txt, sample-apps/07-inventoryService/requirements.txt, sample-apps/08-paymentService/requirements.txt, sample-apps/09-recommendationService/requirements.txt, sample-apps/10-authenticationService/requirements.txt, sample-apps/11-client/api/requirements.txt
Adjusting the protobuf version to be compatible with mysql-connector.
=> Adjusting the protobuf version to be compatible with mysql-connector

cf-templates/cloud9.yaml, cf-templates/ekscluster.yaml, cf-templates/opensearch.yaml, sample-apps/05-databaseService/Dockerfile, sample-apps/05-databaseService/requirements.txt, sample-apps/06-orderService/Dockerfile, sample-apps/06-orderService/requirements.txt, sample-apps/07-inventoryService/Dockerfile, sample-apps/07-inventoryService/requirements.txt, sample-apps/08-paymentService/Dockerfile, sample-apps/08-paymentService/requirements.txt, sample-apps/09-recommendationService/Dockerfile, sample-apps/09-recommendationService/requirements.txt, sample-apps/10-authenticationService/Dockerfile, sample-apps/10-authenticationService/requirements.txt, sample-apps/11-client/Dockerfile, sample-apps/11-client/api/requirements.txt
Python and protobuf version updates.
=> Python and protobuf version updates

sample-apps/05-databaseService/kubernetes/01-deployment.yaml, scripts/02-apply-k8s-manifests.sh
Database start time adjustment.
=> Database start time adjustment

sample-apps/03-mysql/kubernetes/01-deployment.yaml, scripts/02-apply-k8s-manifests.sh
Fixed MySQL version and process of applying k8s manifests.
=> Fixed MySQL version and process of applying k8s manifests

cf-templates/cloud9.yaml, cf-templates/eks.yaml, cf-templates/opensearch.yaml
Amazon EKS upgrade and dependencies.
=> Amazon EKS upgrade and dependencies

cf-templates/opensearch.yaml
=> Nginx version update

README.md, sample-apps/03-mysql/kubernetes/01-deployment.yaml, sample-apps/05-databaseService/kubernetes/01-deployment.yaml
MySQL version update due to EOF.
=> MySQL version update due to EOF

sample-apps/00-fluentBit/kubernetes/fluentbit.yaml, sample-apps/05-databaseService/kubernetes/01-deployment.yaml
Parse adjustment due to CRI runtime and Fluentbit update.
=> Parse adjustment due to CRI runtime and Fluentbit update

sample-apps/11-client/Dockerfile
Bump NPM and Node versions to LTS
Added Browserlist Db update checker
=> Update Dockerfile for client service

cf-templates/cloud9.yaml
Adjusted Cloud9 version to maintain compatibility with existing automations.
=> Image change for Cloud9

cf-templates/base.yaml, cf-templates/cloud9.yaml, cf-templates/ekscluster.yaml, cf-templates/main.yaml, cf-templates/opensearch.yaml, cf-templates/osi.yaml
Cloudformation Infra Updates - Fixed GetPublicIP Lambda, Role duplicity and other minor changes
1- Fixed ServiceLinked Role duplicity when the AWS Account already have a existing Opensearch Domain in base.yaml CFN
2- Updated AmazonLinux ImageId for Cloud9 in cloud9.yaml
3 - Improve lambda code for GetPublicIP for AOS in opensearch.yaml
4- Fixed FunctionName character size in osi.yaml
=> Cloudformation Infra Updates

sample-apps/00-fluentBit/kubernetes/fluentbit.yaml
=> Update fluentbit parsing according to version

sample-apps/00-fluentBit/kubernetes/fluentbit.yaml
=> Update fluentbit filter
